// The 13 livelihood groups ("amatsinda") supported by RW0164 EMLR Nyabinaga.
// Content is kept structured (not hardcoded inline in components) so it is easy
// to edit later and to translate (e.g. adding a Kinyarwanda toggle).
//
// Financial figures are in Rwandan Francs (RWF).
// `image` refers to a file in /public/images (chosen as a representative photo).

export const groups = [
  {
    id: 'abahamya',
    name: 'Abahamya Company Ltd',
    activity: 'Gas trading (cooking gas) & food trading',
    tags: ['Trade', 'Gas', 'Food'],
    image: '/images/image5.jpeg',
    highlight: 'Owns 123 gas cylinders and 2 sales buildings',
    totalAssets: 11898600,
    registered: true,
    details:
      'Owns 123 gas cylinders/bottles (valued at 3,728,000 RWF), 2 buildings used for gas sales (1,361,040 RWF), a boutique/shop business (458,960 RWF), cooking equipment (950,000 RWF), and working capital in their food business (905,600 RWF).',
    breakdown: [
      { label: '123 gas cylinders/bottles', value: 3728000 },
      { label: '2 buildings for gas sales', value: 1361040 },
      { label: 'Boutique / shop business', value: 458960 },
      { label: 'Cooking equipment', value: 950000 },
      { label: 'Food business working capital', value: 905600 },
    ],
  },
  {
    id: 'abahujimbaraga',
    name: 'Abahujimbaraga',
    activity: 'Pig farming',
    tags: ['Livestock', 'Savings'],
    image: '/images/image8.jpeg',
    highlight: '25 members saving 25,000 RWF/week together',
    totalAssets: 5830000,
    registered: true,
    details:
      'Group of 25 members, each saving 1,000 RWF/week (25,000 RWF/week combined, 100,000 RWF/month). Recently one of their sows gave birth to 9 piglets.',
    members: 25,
    savings: 'Each member saves 1,000 RWF/week (100,000 RWF/month combined)',
    breakdown: [
      { label: '2 adult pigs', value: 880000 },
      { label: 'Pig shelters', value: 450000 },
      { label: '8 young pigs', value: 640000 },
      { label: '12 pigs distributed to members', value: 1440000 },
      { label: 'Internal loan fund', value: 750000 },
      { label: 'Savings account', value: 1670000 },
    ],
  },
  {
    id: 'twisungane-ruvumbu',
    name: 'Twisungane Ruvumbu',
    activity: 'Farming & vegetable trade',
    tags: ['Farming', 'Vegetables', 'Trade'],
    image: '/images/image75.jpeg',
    highlight: 'Supplies vegetables to the project every week',
    totalAssets: 5618000,
    registered: true,
    details:
      'Owns 3 farm plots (one worth 1,800,000 RWF planted with sugarcane valued at 650,000 RWF; another worth 850,000 RWF earmarked for coffee). The group sells vegetables and cabbage weekly, supplying the project itself, earning about 68,500 RWF/month. They also rent 3 additional plots (150,000 RWF) planted with carrots, cabbage and seedlings, plus a sugarcane plot (1,250,000 RWF).',
    bankSavings: 850000,
    breakdown: [
      { label: 'Farm plot (sugarcane)', value: 1800000 },
      { label: 'Sugarcane crop', value: 650000 },
      { label: 'Farm plot (for coffee)', value: 850000 },
      { label: 'Rented plots (carrots, cabbage, seedlings)', value: 150000 },
      { label: 'Sugarcane plot', value: 1250000 },
      { label: 'Bank savings', value: 850000 },
    ],
  },
  {
    id: 'teganyejohazaza',
    name: 'Teganyejohazaza',
    activity: 'Sugarcane, cassava farming & goat rearing',
    tags: ['Farming', 'Livestock', 'Coffee'],
    image: '/images/image13.jpeg',
    highlight: '23 goats and 100 coffee trees',
    totalAssets: 11989000,
    registered: true,
    details:
      '23 members, each saving 1,000 RWF/month (23,000 RWF/month combined). Owns 23 goats (4,255,000 RWF), 100 coffee trees (1,800,000 RWF), 1 pig (315,000 RWF), sugarcane harvested twice a year (600,000 RWF), and income from coffee harvest (350,000 RWF).',
    members: 23,
    savings: 'Each member saves 1,000 RWF/month (23,000 RWF/month combined)',
    bankSavings: 852000,
    loanedToMembers: 497000,
    breakdown: [
      { label: '23 goats', value: 4255000 },
      { label: '100 coffee trees', value: 1800000 },
      { label: '1 pig', value: 315000 },
      { label: 'Sugarcane (harvested twice a year)', value: 600000 },
      { label: 'Coffee harvest income', value: 350000 },
      { label: 'Bank savings', value: 852000 },
      { label: 'Loaned to members', value: 497000 },
    ],
  },
  {
    id: 'twikenure-bunyamanza',
    name: 'Twikenure Bunyamanza',
    activity: 'Coffee, tomato, cassava & banana farming',
    tags: ['Coffee', 'Farming', 'Tomatoes'],
    image: '/images/image22.jpeg',
    highlight: '1,050 coffee trees — the largest group by assets',
    totalAssets: 29437000,
    registered: true,
    details:
      '13 members, each saving 2,000 RWF/month (26,000 RWF/month combined). They also grow mulching grass to protect their coffee plants. Owns 4 farm plots (total 9,830,000 RWF), a tomato plot (407,000 RWF), 1,050 coffee trees (15,750,000 RWF), and 2 goats (306,400 RWF). Recent harvest income: 550,000 RWF (tomatoes) and 600,000 RWF (coffee).',
    members: 13,
    savings: 'Each member saves 2,000 RWF/month (26,000 RWF/month combined)',
    bankSavings: 2000000,
    breakdown: [
      { label: '4 farm plots', value: 9830000 },
      { label: 'Tomato plot', value: 407000 },
      { label: '1,050 coffee trees', value: 15750000 },
      { label: '2 goats', value: 306400 },
      { label: 'Tomato harvest income', value: 550000 },
      { label: 'Coffee harvest income', value: 600000 },
      { label: 'Bank savings', value: 2000000 },
    ],
  },
  {
    id: 'twikenure-mushungo',
    name: 'Twikenure Mushungo',
    activity: 'Coffee, tomato farming & cassava trade',
    tags: ['Coffee', 'Tomatoes', 'Trade'],
    image: '/images/image15.jpeg',
    highlight: 'Coffee, cassava trade and pig farming combined',
    totalAssets: 7944200,
    registered: true,
    details:
      'Owns a tomato plot (538,400 RWF), 134 coffee trees (1,608,000 RWF), and pays 180,000 RWF/month for fertilizer. Owns a farm (1,980,000 RWF), a cassava trading business (980,000 RWF), pig farming (360,000 RWF), and recent harvest income of 780,000 RWF (coffee).',
    bankSavings: 380000,
    breakdown: [
      { label: 'Tomato plot', value: 538400 },
      { label: '134 coffee trees', value: 1608000 },
      { label: 'Farm', value: 1980000 },
      { label: 'Cassava trading business', value: 980000 },
      { label: 'Pig farming', value: 360000 },
      { label: 'Coffee harvest income', value: 780000 },
      { label: 'Bank savings', value: 380000 },
    ],
  },
  {
    id: 'jyambere',
    name: 'Jyambere',
    activity: 'Maize, beans & soy farming',
    tags: ['Farming', 'Maize', 'Beans'],
    image: '/images/image25.jpeg',
    highlight: 'Grows maize, beans, soy, carrots and onions',
    totalAssets: 5686960,
    registered: true,
    details:
      'Rents 2 farm plots (267,000 RWF and 365,000 RWF), owns 1 plot (1,650,000 RWF), a maize harvest worth 450,000 RWF, an internal loan fund of 354,000 RWF, a beans harvest of 168,000 RWF, and a carrot/onion plot (620,000 RWF).',
    bankSavings: 828000,
    breakdown: [
      { label: 'Rented farm plot 1', value: 267000 },
      { label: 'Rented farm plot 2', value: 365000 },
      { label: 'Owned farm plot', value: 1650000 },
      { label: 'Maize harvest', value: 450000 },
      { label: 'Internal loan fund', value: 354000 },
      { label: 'Beans harvest', value: 168000 },
      { label: 'Carrot / onion plot', value: 620000 },
      { label: 'Bank savings', value: 828000 },
    ],
  },
  {
    id: 'ubwiza-nyabinaga',
    name: 'Ubwiza Nyabinaga',
    activity: 'Liquid soap production',
    tags: ['Crafts', 'Soap', 'Poultry'],
    image: '/images/image30.jpeg',
    highlight: '15 members making liquid soap & raising 30 chickens',
    totalAssets: 1733500,
    registered: true,
    details:
      'Started by saving 500 RWF/month and have since increased to 1,000 RWF/month (15,000 RWF/month combined). Each member received 2 chickens (7,500 RWF each).',
    members: 15,
    savings: 'Grew from 500 to 1,000 RWF/month per member (15,000 RWF/month combined)',
    bankSavings: 235630,
    breakdown: [
      { label: '30 chickens', value: 330000 },
      { label: 'Group savings', value: 266000 },
      { label: 'Soap stock', value: 48000 },
      { label: 'Rented farm plot', value: 55000 },
      { label: 'Soap-making equipment', value: 285000 },
      { label: 'Bank savings', value: 235630 },
    ],
  },
  {
    id: 'dukundumurimo-babyeyi',
    name: 'Dukundumurimo Babyeyi',
    activity: 'Basket & handicraft weaving; rice farming',
    tags: ['Crafts', 'Weaving', 'Rice'],
    image: '/images/image32.jpeg',
    highlight: '10 sacks of rice plus handwoven crafts',
    totalAssets: 7353620,
    registered: true,
    details:
      'Runs several activities: soy farming (55,000 RWF), maize farming (78,000 RWF), cassava farming (159,000 RWF), a rented farm plot (260,000 RWF), 741,300 RWF in savings, 238,700 RWF loaned to members, and 10 sacks of rice (1,800,000 RWF). Rice farming alone contributes 1,930,860 RWF.',
    bankSavings: 748900,
    breakdown: [
      { label: 'Soy farming', value: 55000 },
      { label: 'Maize farming', value: 78000 },
      { label: 'Cassava farming', value: 159000 },
      { label: 'Rented farm plot', value: 260000 },
      { label: 'Group savings', value: 741300 },
      { label: 'Loaned to members', value: 238700 },
      { label: '10 sacks of rice', value: 1800000 },
      { label: 'Bank savings', value: 748900 },
    ],
  },
  {
    id: 'tuzamurane-kigarama',
    name: 'Tuzamurane Kigarama',
    activity: 'Pig farming',
    tags: ['Livestock', 'Savings'],
    image: '/images/image42.jpeg',
    highlight: 'Started with only a name — now owns a growing herd',
    totalAssets: 2150500,
    registered: true,
    details:
      'The group started with nothing at all — just a name. After members were encouraged to begin saving together, they pooled funds and bought their first pig, which has since given birth to 8 piglets.',
    members: 23,
    savings: 'Each member saves 1,000 RWF/month (23,000 RWF/month combined)',
    bankSavings: 460000,
    breakdown: [
      { label: '1 adult pig', value: 283000 },
      { label: '9 young pigs', value: 450000 },
      { label: 'Member savings', value: 386500 },
      { label: '3 additional pigs purchased', value: 150000 },
      { label: 'Rented farm plot', value: 50000 },
      { label: 'Internal loan fund', value: 300000 },
      { label: 'Bank savings', value: 460000 },
    ],
  },
  {
    id: 'twitezimbere-ruvumbu',
    name: 'Twitezimbere Ruvumbu',
    activity: 'Soy & beans farming, forestry',
    tags: ['Farming', 'Forestry', 'Beans'],
    image: '/images/image40.jpeg',
    highlight: 'Owns a forest plot generating forestry income',
    totalAssets: 5176280,
    registered: true,
    details:
      '9 members, each saving 1,000 RWF/month (9,000 RWF/month combined). Owns a forest plot (1,500,000 RWF), soy crop (42,000 RWF), 30kg of beans (30,000 RWF), and recent harvest income from beans (31,200 RWF), soy (25,000 RWF), and forestry income (4,518,080 RWF).',
    members: 9,
    savings: 'Each member saves 1,000 RWF/month (9,000 RWF/month combined)',
    breakdown: [
      { label: 'Forest plot', value: 1500000 },
      { label: 'Soy crop', value: 42000 },
      { label: '30kg of beans', value: 30000 },
      { label: 'Beans harvest income', value: 31200 },
      { label: 'Soy harvest income', value: 25000 },
      { label: 'Forestry income', value: 4518080 },
    ],
  },
  {
    id: 'ngamburuzabukene',
    name: 'Ngamburuzabukene',
    activity: 'Small joint retail trade',
    tags: ['Trade', 'Retail', 'Savings'],
    image: '/images/image72.jpeg',
    highlight: 'Shared shop selling grains, oil, vegetables & fruit',
    totalAssets: 1800000,
    approximate: true,
    registered: true,
    details:
      '11 members, saving 5,100 RWF/month per member. The group runs a shared small trading business selling beans, rice, soy, cooking oil, groundnuts, vegetables, and fruit.',
    members: 11,
    savings: 'Each member saves 5,100 RWF/month',
    breakdown: [],
  },
  {
    id: 'ejo-heza',
    name: 'Ejo Heza',
    activity: 'Registered livelihood group',
    tags: ['Registered'],
    image: '/images/image3.jpeg',
    highlight: 'A legally registered member group',
    totalAssets: 0,
    registered: true,
    details:
      'A registered livelihood group and one of the legally registered groups with notarized statutes. Detailed financials were not itemized in the source material, but it operates alongside the other member groups.',
    breakdown: [],
  },
]

// Names of the officially registered groups (legal, notarized statutes).
export const registeredGroupNames = [
  'Teganyejohazaza',
  'Twikenure Bunyamanza',
  'Twikenure Mushungo',
  'Jyambere',
  'Tuzamurane',
  'Dukundumurimo Babyeyi',
  'Ngamburuzabukene',
  'Abahujimbaraga',
  'Twitezimbere Ruvumbu',
  'Twisungane Ruvumbu',
  'Abahamya Company',
  'Ejo Heza',
]

// Helper for currency formatting used across the site.
// English uses the "RWF" code; French and Kinyarwanda use "FRW".
export const formatRWF = (value, lang = 'en') => {
  const number = new Intl.NumberFormat('en-US').format(value)
  const unit = lang === 'en' ? 'RWF' : 'FRW'
  return `${number} ${unit}`
}
